# Generated by Django 2.0 on 2018-01-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=16)),
                ('face_photo_url', models.CharField(blank=True, max_length=400)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('is_guide', models.BooleanField(default=False)),
                ('is_certified', models.BooleanField(default=False)),
                ('is_certified_guide', models.BooleanField(default=False)),
            ],
        ),
    ]
