# Generated by Django 2.0 on 2018-01-15 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Users.UserInformation')),
                ('user_phone', models.CharField(blank=True, max_length=20)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('user_wechat', models.CharField(blank=True, max_length=20)),
                ('user_whatsapp', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
