# Generated by Django 2.0 on 2018-01-16 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20180116_0456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercontact',
            old_name='id',
            new_name='user',
        ),
    ]
