# Generated by Django 2.0 on 2018-01-17 04:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20180116_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBackground',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Users.UserInformation')),
                ('user_gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('NA', 'Not sure')], max_length=2)),
                ('user_home_country', models.CharField(blank=True, max_length=30)),
                ('user_home_province', models.CharField(blank=True, max_length=30)),
                ('user_home_city', models.CharField(blank=True, max_length=30)),
                ('user_now_country', models.CharField(blank=True, max_length=30)),
                ('user_now_province', models.CharField(blank=True, max_length=30)),
                ('user_now_city', models.CharField(blank=True, max_length=30)),
                ('user_time', models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.RenameField(
            model_name='userinformation',
            old_name='created_time',
            new_name='join_time',
        ),
    ]
