# Generated by Django 2.0 on 2018-01-17 04:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20180117_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbackground',
            name='user_time',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)]),
        ),
    ]
