# Generated by Django 2.0 on 2018-01-17 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20180117_0406'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEducation',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Users.UserInformation')),
                ('user_degree', models.CharField(blank=True, choices=[('El', 'Elementary'), ('Se', 'Secondary'), ('Ba', 'Bachelor'), ('Ma', 'Master'), ('DC', 'Doctor'), ('PD', 'Post Doctor')], max_length=2)),
                ('user_school', models.CharField(blank=True, max_length=50)),
                ('user_major', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserLanguage',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Users.UserInformation')),
                ('user_language1', models.CharField(blank=True, max_length=20)),
                ('user_skill1', models.CharField(blank=True, choices=[('B', 'Beginning'), ('M', 'Mother Tougne'), ('P', 'Proficient'), ('I', 'Influent'), ('L', 'Limilted')], max_length=1)),
                ('user_language2', models.CharField(blank=True, max_length=20)),
                ('user_skill2', models.CharField(blank=True, choices=[('B', 'Beginning'), ('M', 'Mother Tougne'), ('P', 'Proficient'), ('I', 'Influent'), ('L', 'Limilted')], max_length=1)),
                ('user_language3', models.CharField(blank=True, max_length=20)),
                ('user_skill3', models.CharField(blank=True, choices=[('B', 'Beginning'), ('M', 'Mother Tougne'), ('P', 'Proficient'), ('I', 'Influent'), ('L', 'Limilted')], max_length=1)),
            ],
        ),
    ]
