# Generated by Django 2.0 on 2018-01-17 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_usereducation_userlanguage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGuide',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Users.UserInformation')),
                ('certified_guide', models.BooleanField(default=False)),
                ('guide_certification_url', models.CharField(blank=True, max_length=400)),
                ('car_photo_url', models.CharField(blank=True, max_length=400)),
                ('car_plate_number', models.CharField(blank=True, max_length=10)),
                ('start_time', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserIdentity',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Users.UserInformation')),
                ('user_passport', models.CharField(blank=True, max_length=15)),
                ('passport_photot_url', models.CharField(blank=True, max_length=400)),
                ('passport_issued_country', models.CharField(blank=True, max_length=30)),
                ('user_identity', models.CharField(blank=True, max_length=20)),
                ('identity_photo_url', models.CharField(blank=True, max_length=400)),
                ('identity_issued_country', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='userlanguage',
            name='user_skill1',
            field=models.CharField(blank=True, choices=[('M', 'Mother Tougne'), ('P', 'Proficient'), ('I', 'Influent'), ('B', 'Beginning'), ('L', 'Limilted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='userlanguage',
            name='user_skill2',
            field=models.CharField(blank=True, choices=[('M', 'Mother Tougne'), ('P', 'Proficient'), ('I', 'Influent'), ('B', 'Beginning'), ('L', 'Limilted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='userlanguage',
            name='user_skill3',
            field=models.CharField(blank=True, choices=[('M', 'Mother Tougne'), ('P', 'Proficient'), ('I', 'Influent'), ('B', 'Beginning'), ('L', 'Limilted')], max_length=1),
        ),
    ]
