# Generated by Django 2.0 on 2018-01-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_auto_20180117_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userguide',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userlanguage',
            name='user_skill1',
            field=models.CharField(blank=True, choices=[('L', 'Limilted'), ('P', 'Proficient'), ('B', 'Beginning'), ('I', 'Influent'), ('M', 'Mother Tougne')], max_length=1),
        ),
        migrations.AlterField(
            model_name='userlanguage',
            name='user_skill2',
            field=models.CharField(blank=True, choices=[('L', 'Limilted'), ('P', 'Proficient'), ('B', 'Beginning'), ('I', 'Influent'), ('M', 'Mother Tougne')], max_length=1),
        ),
        migrations.AlterField(
            model_name='userlanguage',
            name='user_skill3',
            field=models.CharField(blank=True, choices=[('L', 'Limilted'), ('P', 'Proficient'), ('B', 'Beginning'), ('I', 'Influent'), ('M', 'Mother Tougne')], max_length=1),
        ),
    ]
