# Generated by Django 2.0 on 2018-01-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_auto_20180118_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='user',
        ),
        migrations.AlterField(
            model_name='userlanguage',
            name='user_skill1',
            field=models.CharField(blank=True, choices=[('P', 'Proficient'), ('B', 'Beginning'), ('I', 'Influent'), ('L', 'Limilted'), ('M', 'Mother Tougne')], max_length=1),
        ),
        migrations.AlterField(
            model_name='userlanguage',
            name='user_skill2',
            field=models.CharField(blank=True, choices=[('P', 'Proficient'), ('B', 'Beginning'), ('I', 'Influent'), ('L', 'Limilted'), ('M', 'Mother Tougne')], max_length=1),
        ),
        migrations.AlterField(
            model_name='userlanguage',
            name='user_skill3',
            field=models.CharField(blank=True, choices=[('P', 'Proficient'), ('B', 'Beginning'), ('I', 'Influent'), ('L', 'Limilted'), ('M', 'Mother Tougne')], max_length=1),
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
