# Generated by Django 2.0 on 2018-01-18 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0014_auto_20180118_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlanguage',
            name='user_skill1',
            field=models.CharField(blank=True, choices=[('B', 'Beginning'), ('M', 'Mother Tougne'), ('P', 'Proficient'), ('L', 'Limilted'), ('I', 'Influent')], max_length=1),
        ),
        migrations.AlterField(
            model_name='userlanguage',
            name='user_skill2',
            field=models.CharField(blank=True, choices=[('B', 'Beginning'), ('M', 'Mother Tougne'), ('P', 'Proficient'), ('L', 'Limilted'), ('I', 'Influent')], max_length=1),
        ),
        migrations.AlterField(
            model_name='userlanguage',
            name='user_skill3',
            field=models.CharField(blank=True, choices=[('B', 'Beginning'), ('M', 'Mother Tougne'), ('P', 'Proficient'), ('L', 'Limilted'), ('I', 'Influent')], max_length=1),
        ),
    ]
