# Generated by Django 2.0 on 2018-01-18 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0016_auto_20180118_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlanguage',
            name='user_skill1',
            field=models.CharField(blank=True, choices=[('I', 'Influent'), ('L', 'Limilted'), ('B', 'Beginning'), ('M', 'Mother Tougne'), ('P', 'Proficient')], max_length=1),
        ),
        migrations.AlterField(
            model_name='userlanguage',
            name='user_skill2',
            field=models.CharField(blank=True, choices=[('I', 'Influent'), ('L', 'Limilted'), ('B', 'Beginning'), ('M', 'Mother Tougne'), ('P', 'Proficient')], max_length=1),
        ),
        migrations.AlterField(
            model_name='userlanguage',
            name='user_skill3',
            field=models.CharField(blank=True, choices=[('I', 'Influent'), ('L', 'Limilted'), ('B', 'Beginning'), ('M', 'Mother Tougne'), ('P', 'Proficient')], max_length=1),
        ),
    ]
