# Generated by Django 2.0 on 2018-01-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0017_auto_20180118_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlanguage',
            name='user_skill1',
            field=models.CharField(blank=True, choices=[('P', 'Proficient'), ('M', 'Mother Tougne'), ('I', 'Influent'), ('L', 'Limilted'), ('B', 'Beginning')], max_length=1),
        ),
        migrations.AlterField(
            model_name='userlanguage',
            name='user_skill2',
            field=models.CharField(blank=True, choices=[('P', 'Proficient'), ('M', 'Mother Tougne'), ('I', 'Influent'), ('L', 'Limilted'), ('B', 'Beginning')], max_length=1),
        ),
        migrations.AlterField(
            model_name='userlanguage',
            name='user_skill3',
            field=models.CharField(blank=True, choices=[('P', 'Proficient'), ('M', 'Mother Tougne'), ('I', 'Influent'), ('L', 'Limilted'), ('B', 'Beginning')], max_length=1),
        ),
    ]
